name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.15.1
    
    - name: Run All Tests
      run: zig build test
    
    - name: Validate RLP Encoding
      run: zig build validate-rlp
    
    - name: Validate RLP Decoding
      run: zig build validate-rlp-decode
    
    - name: Validate RLP Security
      run: zig build validate-rlp-invalid
    
    - name: Run Reference Comparison Tests
      run: |
        pip3 install eth-py-evm || echo "PyEVM not available, skipping reference tests"
        zig build
        ./zig-out/bin/run_reference_tests || echo "Reference tests skipped (PyEVM may not be available)"

  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.15.1
    
    - name: Check Formatting
      run: |
        if ! zig fmt --check .; then
          echo "Code not formatted. Run: zig fmt ."
          exit 1
        fi
    
    - name: Ast Check
      run: find src validation examples -name "*.zig" -exec zig ast-check {} \; || true

  build:
    name: Build All Targets
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.15.1
    
    - name: Build
      run: zig build
    
    - name: Build Examples
      run: |
        zig build run-counter || echo "Counter example build skipped"
        zig build run-storage || echo "Storage example build skipped"
        zig build run-arithmetic || echo "Arithmetic example build skipped"
        zig build run-events || echo "Events example build skipped"
